# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20171228_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_num',
            field=models.IntegerField(verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_publish',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
