# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20171230_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_num',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
